---
title: "LIN 350 Summer 2023"
output: 
  html_document: 
    theme: cosmo
---

**Instructor**: Scott Nelson

**Course Meeting Time**: T/Th 9:30am--12:55pm

**Course Zoom link**: [https://stonybrook.zoom.us/j/4091340647](https://stonybrook.zoom.us/j/4091340647)

**Office Hours**: By appointment (send me an [e-mail]((mailto:scott.nelson@stonybrook.edu)))

***

# Important Links

- [Course Notes](350/CourseNotes.pdf)
- [Brightspace](https://it.stonybrook.edu/services/brightspace)
- [Syllabus](350/LIN350SyllabusSummer2023.pdf)
- [Slack](https://lin350summer2023.slack.com)
- [Presentation Sign-up](https://docs.google.com/spreadsheets/d/1xXhAyL8QtRJlz38SCuRhMD7NcSI8bWonai9Bky0zohQ/edit?usp=sharing)

***

# Class Log

**08/15/2023 **

* We went over [these slides](350/350-ExperimentalMethods.pdf) which discuss various experimental methods for measuring articulatory data. 
* We started project presentations

**08/10/2023 **

* We talked more about vowel normalization from Chapter 9 in the [Course Notes](350/CourseNotes.pdf). We also discussed Chapter 10 which includes the difference between auditory/acoustic theories of speech perception and gestural theories of speech perception and how they might relate to perceptual confusion and the production of rhotics in English.
* We did one final Spectrogram analysis on [this](350/PraatPractice/final.zip  ) sound file.
* We worked on Lab 8 in the [Course Notes](350/CourseNotes.pdf).
[Here](350/Labs/Lab8.zip) are the experiment files. You must run the experiment on yourself and one other person so that you can send me the data by 9:30 am this Sunday (8/13). I will send out the results and more info so you can write up the lab report which is due next Thursday (8/19) by the start of class.

**08/08/2023 **

* ~~We went over Chapter 9 on speech perception with a focus on categorical perception, auditory illusions, and vowel normalization in the [Course Notes](350/CourseNotes.pdf)~~ We talked about [these slides](350/PerceptionSlides.pdf) which will be converted to course notes shortly.
* We discussed this [VOT manipulation script](https://github.com/listenlab/vot) and also went over how to make and run experiments in Praat.
* We worked on Lab 7 in the [Course Notes](350/CourseNotes.pdf). [Here](350/Labs/Lab7.zip) are the experiment files. You must run the experiment on yourself and one other person so that you can send me the data by 9:30 am this Friday (8/11). I will send out the results and more info so you can write up the lab report which is due next Thursday (8/17) by the start of class.


**08/03/2023 **

* We went over Chapter 8 on acoustic cues for place of articulation in the [Course Notes](350/CourseNotes.pdf)
* We discussed spectral measurements in Praat and analyzed [this](350/PraatPractice/poa.zip) sound file
* We worked on Lab 6 in the [Course Notes](350/CourseNotes.pdf). It is due next Thursday (8/10) by the start of class.
* **Reminder:** you must submit a project proposal to me by tomorrow at 5pm.

**08/01/2023 **

* We went over Chapter 7 on acoustic cues for voicing in the [Course Notes](350/CourseNotes.pdf)
* We discussed measuring VOT in Praat and analyzed [this](350/PraatPractice/sto.zip) sound file
* We worked on Lab 5 in the [Course Notes](350/CourseNotes.pdf). It is due next Tuesday (8/8) by the start of class.
* **Reminder:** you must submit a project proposal to me by this Friday, August 4.

**07/27/2023 **

* Today is the halfway mark of the course. We reviewed all of the new material up to this point and *very briefly* discussed the acoustic properties of stress in the [Course Notes](350/CourseNotes.pdf)
* We discussed measuring duration and intensity in Praat and analyzed [this](350/PraatPractice/st.zip) sound file.
* We worked on Lab 4 in the [Course Notes](350/CourseNotes.pdf). It is due next Thursday (8/3) by the start of class.
* **Reminder:** you must submit a project proposal to me by next Friday, August 4.

**07/25/2023 **

* We went over Chapter 5 on the Acoustic Theory of Speech Production in the [Course Notes](350/CourseNotes.pdf)
* We discussed different ways of measuring formants in Praat and analyzed [this](350/PraatPractice/pbzj.zip) sound file.
* We worked on Lab 3 in the [Course Notes](350/CourseNotes.pdf). It is due next Tuesday (8/1) by the start of class.
* To make your vowel plot for part 1, use [this page](vowelplotting.html). It requires your data to be in csv format. An example is [here](350/vowels.csv). 
  * In excel/numbers/google sheets you can make a spreadsheet with three columns labeles `VOWEL`, `F1`, and `F2`. The vowel column should contain the vowel label, the F1 column should contain the mean F1 for each vowel, and the F2 column should contain the mean F2 for each vowel. You can then either save or export that spreadsheet as a csv. Once you do that, you can upload it to the page above and it will create a vowel plot for you. Right click and save the figure and you're done. You can now add it to your lab report.

**07/20/2023 **

* We went over Chapter 4 on Lexical Tone + Contrast in the [Course Notes](350/CourseNotes.pdf)
* We discussed automatic analysis and how to draw pictures in Praat and analyzed [this](350/PraatPractice/PUT.wav.zip) sound file. [Here](350/PraatPractice/VowelDuration.praat) is the script we wrote together that automatically measures vowel duration.
* We worked on Lab 2 in the [Course Notes](350/CourseNotes.pdf). Download the sound files [here](350/Labs/Lab2.zip). It is due next Thursday (7/27) by the start of class

**07/18/2023 **

* We went over Chapter 3 on f0 in the [Course Notes](350/CourseNotes.pdf)
* We discussed how to measure f0 in Praat and analyzed [this](350/PraatPractice/potato.wav.zip) sound file
* We worked on Lab 1 in the [Course Notes](350/CourseNotes.pdf). It is due next Tuesday (7/25) by the start of class

**07/11/2023 & 07/13/2023**

* Week 1 is online & asynchronous because I am out of town
* I will be on Zoom from 12-1pm on 7/11 and 7/13 for anyone who would like to meet with me.
* Your tasks for week 1:
    + Come to one of the Zoom meetings to introduce yourself. If you are unable, please send me an email introducing yourself instead.
    + Read the [syllabus](350/LIN350SyllabusSummer2023.pdf)
    + Join the [course slack channel](https://join.slack.com/t/lin350summer2023/shared_invite/zt-1wlogdm2b-JtDb~jPe89ky1jLfmbZeUg)
    + Sign up for a presentation slot [here](https://docs.google.com/spreadsheets/d/1xXhAyL8QtRJlz38SCuRhMD7NcSI8bWonai9Bky0zohQ/edit?usp=sharing)
    + Watch the intro to the course [video](350/intro.mp4)
    + Watch the review of articulatory phonetics [video](350/review-articulatory.mp4)
    + Watch the review of acoustic phonetics [video](350/review-acoustics.mp4)
    + Watch the intro to Praat [video](350/intro-praat.mp4)
    + Review Chapters 1 & 2 and Appendix A of the [course notes](350/CourseNotes.pdf)
    + Complete and submit Lab 0; download files [here](350/Labs/Lab0.zip)

