---
title: "PPCC Research Group"
output: 
  html_document: 
    theme: cosmo
---

The **P**(honology), **P**(honetics), **C**(omputation), and **C**(ognition) **Research Group** is led 
by Scott Nelson at the University of Illinois Urbana-Champaign.  The research focus of this group is on the relationship between *phonological* and *phonetic knowledge*. We largely approach things *computationally* and are interested in the implications of what we find for general linguistic *cognition*. 

The group meets every other week for two hours. 
Meetings are broken down into three 40 minute chunks.
One chunk is for a group member to share their ongoing work with the group.
Another chunk is for a group member to lead a discussion on a recently published (or pre-print) paper
relevant to the group's interests.
The final chunk is for a group member to teach a skill (programming language, software, mathematical approach, ...).

## Spring 2026 Meetings

|Date|Research Presentation| Paper Presentation| Skill Presentation|
|:---:|:---:|:---:|:---:|
|1/28|Scheduling Meeting |na.|na.|
|2/11|Matthew and Scott on Tier-Based Functions w/ BMRS|Anna on [Cho (2025)](https://www.sciencedirect.com/science/article/abs/pii/S0095447025000373)|Scott on Information Theory \(G&K Ch. 1\)|
2/25|Mikhael on TSL Poetry Experiments|Daniel on [Kawahara & Kumagai (2025)](https://www.journal-labphon.org/article/id/10808/)|--|
|3/11|Angie on Malay Morphophonology|Ryan on [Richmond (2024)](https://onlinelibrary.wiley.com/doi/full/10.1111/mila.12521)|Scott on Bayesian Updating \(G&K Ch. 2\)|
|3/25|Daniel on Rendaku + Lyman's Law with BMRS|Mikhael on [Swanson (2025)](https://mol2025.molweb.xyz/docs/mol2025_swanson.pdf)|Scott on Functions and Representations \(G&K Ch. 3+4\)|
|4/8|CLS Week|CLS Week|CLS Week|
|4/22|Ryan on Phonetic Category Learning|Angie on [Czarnecki (2025)](https://openpublishing.library.umass.edu/scil/article/id/3162/)|Scott on Symbols and Procedures \(G&K Ch. 5+6\)|
|5/6|Anna on tbd.|Matthew on [Hu (2025)](https://openpublishing.library.umass.edu/scil/article/id/3157/)|Scott on Architectures and Data Structures \(G&K Ch. 8+9\)|

## Fall 2025 Meetings

|Date|Research Presentation| Paper Presentation| Skill Presentation|
|:---:|:---:|:---:|:---:|
|8/27|[Scott on PPCC](PPCC/Intro-2025.pdf) |na.|na.|
|9/10|Anna AMP Practice Talk|Matthew on [Yolyan (2025)](https://mol2025.molweb.xyz/docs/mol2025_yolyan.pdf)|Yinglun on LaTeX|
|9/24|Yinglun on Re-Analyzing the Expressivity of SK Korean Tone Plateuing|Angie on [Meyers et al. (2025)](https://www.sciencedirect.com/science/article/pii/S0749596X25000427)|Scott on Markdown|
|10/8|Matthew on Tier-Based Functions with BMRS|Yinglun on [Joo & Jardine (2025)](https://openpublishing.library.umass.edu/scil/article/id/3124/)|Scott on [Weighted Logic (and more!)](PPCC/GradientFLT.pdf)|
|10/22|Mikhael on Computing Rhyme|na.|na.|
|11/5|Scott on Vowel Harmony Typology w/ BMRS|Anna on [Levenstein et al. (2024)](https://link.springer.com/article/10.1007/s42113-024-00219-3) |Scott on [Bayesian Statistics](PPCC/BayesianStats.pdf)|
|11/19|Angie on Malay Morphophonology and BMRS|(Ryan on [Wetzel & Kurz (2025)](https://www.sciencedirect.com/science/article/pii/S0010027725000873))|n.a|
|12/3|Ryan on Real-Time Automaton for Phonetic Categorization|Mikhael on [Danis (2025)](https://openpublishing.library.umass.edu/amphonology/article/id/3022/)|Scott on Computational Learning Theory|