---
title: "Statistics Mini-Course Summer 2023"
output: 
  html_document: 
    theme: cosmo
---
***

**Instructor**: Scott Nelson

**Course Meeting Time**: 12:00--1:00pm T/F

**Course Zoom link**: [https://stonybrook.zoom.us/j/4091340647](https://stonybrook.zoom.us/j/4091340647)

**Office Hours**: By appointment (send me an [e-mail]((mailto:scott.nelson@stonybrook.edu)))

***

# Important Links

- [Datacamp](https://www.datacamp.com)
- [The R-Project](https://www.r-project.org)
- [RStudio Desktop](https://posit.co/download/rstudio-desktop/)
- [RStudio Cloud](https://login.rstudio.cloud)


***

# Overview

This minicourse will run for three weeks from May 21 to June 9. Individual lessons will be assigned using the website Datacamp which is an online learning platform. Each week we will on Monday and Friday from 12:00-1:00pm via Zoom to discuss and review the material. Completion of lessons is self-paced, but it is expected that the assigned lessons will be completed before the Zoom meetings. A list of topics and schedule is given below.


***

# Schedule
|Week|Day|Lessons|R File|Zoom
|:--:|:-:|:-----:|:----:|:--:
|1|5/23|Introduction to R, Introduction to the Tidyverse|[Session1.R](files/StatsSU23/Session1.R)|[Session 1 Recording](https://stonybrook.zoom.us/rec/share/tBEX4MqYbH5V5AOCUzRzxRUQH4zJIyIiR187NpxXevcYEOdnAXyIJL1HcHTZ0COm.qOf-I0cJziGViGoS?startTime=1684857888000)
|1|5/26|Introduction to Statistics in R, Foundations of Probability in R| [Session2.R](files/StatsSU23/Session2.R)|[Session 2 Recording](https://stonybrook.zoom.us/rec/share/g0GKboAFb7nJL8TQ42yLA13rPrU_GdvyYGfPzAXUBZ9nvlx3U4pPAyH1Xd-_UhWt.GOPOoQV6mxcX8yYl?startTime=1685117093000)
|2|5/30|Introduction to Regresssion in R, Intermediate Regression in R|[Session3.R](files/StatsSU23/Session3.R)|[Session 3 Recording](https://stonybrook.zoom.us/rec/share/q0vf_4gGgdQ9CtP1uwm8WINEvqIbrQcramp0e39Ui9iFSfN3yIVQZUdHu-cGfttk.8P_Wsk3fHgV0H-yX)
|2|6/2|Sampling in R, Hypothesis Testing in R|[Session4.R](files/StatsSU23/Session4.R)|[Session 4 Recording](https://stonybrook.zoom.us/rec/share/hPU5BWDnanx-wZg2jHuyU_Wy9oyZY0TdTQu90BZsFydDFnrbcXpg7IXAdNAYwKtq.kppTqOISmSs-_v1d)
|3|6/6|Experimental Design in R, Hierarchical and Mixed Effect Models in R|[Session5.R](files/StatsSU23/Session5.R)|[Session 5 Recording](https://stonybrook.zoom.us/rec/share/U95gi4bwGa6bSTzl4KZYpwMFzIdfQ7yS16Lo8nxCIrehige6EwEBqeV5bL2YwLpf.MqiKxEOMWuwWI49J)
|3|6/9|Fundamentals of Bayesian Data Analysis in R, Foundations of Inference in R|

***

# Further Reading

### Linguistics Related Statistics Textbooks

- [Statistics for Linguists: An Introduction Using R](https://www.routledge.com/Statistics-for-Linguists-An-Introduction-Using-R/Winter/p/book/9781138056091)
- [Regression Modeling for Linguistic Data](https://mitpress.mit.edu/9780262045483/regression-modeling-for-linguistic-data/)
  - [Free pdf](https://osf.io/3827m)
  - [Older free online course notes](http://people.linguistics.mcgill.ca/~morgan/qmld-book/)
  
### General Statistics Textbooks

- [All of Statistics](https://link.springer.com/book/10.1007/978-0-387-21736-9)
- [Statistical Inference](https://www.cengage.com/c/statistical-inference-2e-casella/9780534243128/)
- [Regression and Other Stories](https://www.cambridge.org/highereducation/books/regression-and-other-stories/DD20DD6C9057118581076E54E40C372C#overview)

### Bayesian Statistics Textbooks

- [Statistical Rethinking](https://www.routledge.com/Statistical-Rethinking-A-Bayesian-Course-with-Examples-in-R-and-STAN/McElreath/p/book/9780367139919)
- [Doing Bayesian Data Analysis](https://www.elsevier.com/books/doing-bayesian-data-analysis/kruschke/978-0-12-405888-0)

### Journal Special Issues

- [Journal of Phonetics: Emerging Data Analysis in Phonetic Sciences](https://www.sciencedirect.com/journal/journal-of-phonetics/special-issue/10357FT5MD0)
- [Journal of Memory and Language: Emerging Data Analysis](https://www.sciencedirect.com/journal/journal-of-memory-and-language/vol/59/issue/4)

### Online Open Courses

- [Improving Your Statistical Inferences](https://lakens.github.io/statistical_inferences/)
- [An Introduction to Data Analysis](https://michael-franke.github.io/intro-data-analysis/index.html)